[project]
name = "setuptools-lean"
version = "0.1.1.dev1"
description = "Setuptools plugin for Lean/Nerodia Python extensions"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
  {name = "Mac Malone", email = "mac@lean-fro.org"},
]
keywords = ["distutils", "setuptools", "lean", "nerodia"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.14",
  "Operating System :: POSIX",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
]
requires-python = ">=3.14"
dependencies = ["setuptools"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.entry-points."setuptools.finalize_distribution_options"]
setuptools-lean = "setuptools_lean:finalize_lean"

[project.entry-points."distutils.commands"]
build_lean = "setuptools_lean:build_lean"
